sudo: required
services:
  - docker

before_install:
  - docker build -t nathansun/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true nathansun/docker-react npm run test -- --coverage